### ISSUE TITLE
Kobo Libra Color new database return less data than before

### ISSUE THREAD

**Issue by eliascotto** [elias94/export-kobo#6]
As explained here https://github.com/eliascotto/export-kobo/pull/5#issuecomment-2241377128

Testing results:

| Program version | Old DB | New DB |
| --- | --- | --- |
| Original | (Error) | 214 lines, 7.3k |
| Current | 758 lines, 27k | 214 lines, 7.3k |

@steeltrap maybe having a SQL file would be helpful to see what changed.

**Comment by steeltrap** [comment]
I used an SQL inspector and confirmed that the newer database (per table above) still contains all of the annotations - so there must be a bug involved somewhere. 

@eliascotto  is there a way to provide the two files without sharing here? (They do contain some personal information, so would prefer not to share them publicly!)

**Comment by eliascotto** [comment]
@steeltrap you can send it to `scottoelia@proton.me`.
Thanks

**Comment by steeltrap** [comment]
Thank you! I've sent files via email to that address today.

**Comment by steeltrap** [comment]
@eliascotto  I have tested [patch-db-v175](https://github.com/eliascotto/export-kobo/tree/patch-db-v175) and it appears to be working. I tested with the two versions of the database used for previous testing and it now returns results expected. 

I separately tested with an updated version of the database with a new sample addition - and it works as expected. Nice work!
